name: Host - Recaptcha Rooms

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: haxball-recaptcha-hosts
  cancel-in-progress: false

jobs:
  run-script:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 15
      matrix:
        include:
          - recaptcha_token: "thr1.AAAAAGmQvoRtNyf2pzXDrw.Hl67H9b1C7I"
            index: 0
          - recaptcha_token: "thr1.AAAAAGmQvoz89A7ZlotBUg.hxNWzvYp7ZM"
            index: 1
          - recaptcha_token: "thr1.AAAAAGmQvpFMLKmuQNj6bA.K3EHpqnyboI"
            index: 2
          - recaptcha_token: "thr1.AAAAAGmQv0s5MgsFfpc8vA.xvnJgAjhuIc"
            index: 3
          - recaptcha_token: "thr1.AAAAAGmQv1-rzfs96dVFzw.R-SnjgR2ksk"
            index: 4
          - recaptcha_token: "thr1.AAAAAGmQv3ENhq5IAQdKxQ.ko6NrdG9oJE"
            index: 5
          - recaptcha_token: "thr1.AAAAAGmQv4uWIRF0KNC-7g.a4NnVGwxXl4"
            index: 6
          - recaptcha_token: "thr1.AAAAAGmQv5gmdBK58HhVoA.Et7mU5c1UkI"
            index: 7
          - recaptcha_token: "thr1.AAAAAGmQv6KBkIzCmNFCTA.LflrugJoVAM"
            index: 8
          - recaptcha_token: "thr1.AAAAAGmQv8GNJw0_U7SxVQ.ryOREQH2sEQ"
            index: 9
          - recaptcha_token: "thr1.AAAAAGmQv8Eq2cDRgQAouQ.uysCCSP07Ek"
            index: 10
          - recaptcha_token: "thr1.AAAAAGmQv9f7cGW0xlal2g.H4yHEJv8QUE"
            index: 11
          - recaptcha_token: "thr1.AAAAAGmQv_TB2VeEnSY5gg.hZiS2S1jgpc"
            index: 12
          - recaptcha_token: "thr1.AAAAAGmQv_WCn0Fq5gdrpA.bJlqGTeiUbU"
            index: 13

    steps:
      - name: üß© Checkout repo
        uses: actions/checkout@v4

      - name: üßπ Limpiar entorno previo
        run: rm -rf node_modules package-lock.json

      - name: ‚öôÔ∏è Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: üì¶ Instalar dependencias
        run: npm install

      - name: üöÄ Ejecutar host
        run: node hosts.js
        env:
          INDEX: ${{ matrix.index }}
          RECAPTCHA_TOKEN: ${{ matrix.recaptcha_token }}
          ROOM_PASSWORD: ""
          PLAYER_NAME: "Teleese"
          PLAYER_AVATAR: "üëΩ"
