name: Host - Recaptcha Rooms

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: haxball-recaptcha-hosts
  cancel-in-progress: false

jobs:
  run-script:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 11
      matrix:
        include:
          - recaptcha_token: "thr1.AAAAAGlSm5zDhSMxJguAaQ.bgZ2gnDddvc"
            index: 0
          - recaptcha_token: "thr1.AAAAAGlSm6uO7GcnF2c12w.cwfKH24nszA"
            index: 1
          - recaptcha_token: "thr1.AAAAAGlSm8OBDiCogoz8dg.13eYv7Dh8bg"
            index: 2
          - recaptcha_token: "thr1.AAAAAGlSm9rtTcdajHD8KA.gym8zYJXZmI"
            index: 3
          - recaptcha_token: "thr1.AAAAAGlSm-XdARO9Y4lDoQ.V0bQMV_7pTY"
            index: 4
          - recaptcha_token: "thr1.AAAAAGlSm-yshFeNGbu29g.9j7U-farTWY"
            index: 5
          - recaptcha_token: "thr1.AAAAAGlSm_yqg3N94Hm5aQ.lm1Pu_uYxRs"
            index: 6
          - recaptcha_token: "thr1.AAAAAGlSnEFwifLW_lb9dQ.8WOMkjmW41g"
            index: 7
          - recaptcha_token: "thr1.AAAAAGlSnEpa_TBR0r7fqg.bGpXCO5HQW0"
            index: 8
          - recaptcha_token: "thr1.AAAAAGlSnFcLVREvRsE4Cw.Fowm91y9Fps"
            index: 9
          - recaptcha_token: "thr1.AAAAAGlSnGwNbXtXfNig3Q.5sGHSAYHn_M"
            index: 10

    steps:
      - name: üß© Checkout repo
        uses: actions/checkout@v4

      - name: üßπ Limpiar entorno previo
        run: rm -rf node_modules package-lock.json

      - name: ‚öôÔ∏è Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: üì¶ Instalar dependencias
        run: npm install

      - name: üöÄ Ejecutar host
        run: node hosts.js
        env:
          INDEX: ${{ matrix.index }}
          RECAPTCHA_TOKEN: ${{ matrix.recaptcha_token }}
          ROOM_PASSWORD: ""
          PLAYER_NAME: "Teleese"
          PLAYER_AVATAR: "üëΩ"
