name: nofake

on:
  workflow_dispatch:
    inputs:
      haxball_rooms:
        description: 'Links de las salas (separados por coma)'
        required: true
        default: 'https://www.haxball.com/play?c=1n05nbF698Q,https://www.haxball.com/play?c=2,https://www.haxball.com/play?c=3'
      mensaje:
        description: 'Mensaje principal de los bots'
        required: true
        default: 'Raid por Stefano365p'
      llamar_admin:
        description: 'Mensaje para llamar al administrador'
        required: true
        default: 'admin'
      password:
        description: 'Contrase√±a de la sala (opcional)'
        required: false
        default: ''

jobs:
  run-bots:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 27
      matrix:
        include:
          - { job_index: 0, job_id: nosoykamikaze:)1 }
          - { job_index: 1, job_id: nosoykamikaze:)2 }
          - { job_index: 2, job_id: nosoykamikaze:)3 }
          - { job_index: 3, job_id: nosoykamikaze:)4 }
          - { job_index: 4, job_id: nosoykamikaze:)5 }
          - { job_index: 5, job_id: nosoykamikaze:)6 }
          - { job_index: 6, job_id: nosoykamikaze:)7 }
          - { job_index: 7, job_id: nosoykamikaze:)8 }
          - { job_index: 8, job_id: nosoykamikaze:)9 }
          - { job_index: 9, job_id: nosoykamikaze:)10 }
          - { job_index: 10, job_id: nosoykamikaze:)11 }
          - { job_index: 11, job_id: nosoykamikaze:)12 }
          - { job_index: 12, job_id: nosoykamikaze:)13 }
          - { job_index: 13, job_id: nosoykamikaze:)14 }
          - { job_index: 14, job_id: nosoykamikaze:)15 }
          - { job_index: 15, job_id: nosoykamikaze:)16 }
          - { job_index: 16, job_id: nosoykamikaze:)17 }
          - { job_index: 17, job_id: nosoykamikaze:)18 }
          - { job_index: 18, job_id: nosoykamikaze:)19 }
          - { job_index: 19, job_id: nosoykamikaze:)20 }
          - { job_index: 20, job_id: nosoykamikaze:)21 }
          - { job_index: 21, job_id: nosoykamikaze:)22 }
          - { job_index: 22, job_id: nosoykamikaze:)23 }
          - { job_index: 23, job_id: nosoykamikaze:)24 }
          - { job_index: 24, job_id: nosoykamikaze:)25 }
          - { job_index: 25, job_id: nosoykamikaze:)26 }
          - { job_index: 26, job_id: nosoykamikaze:)27 }
          - { job_index: 27, job_id: nosoykamikaze:)28 }
          - { job_index: 28, job_id: nosoykamikaze:)29 }
          - { job_index: 29, job_id: nosoykamikaze:)30 }
          - { job_index: 30, job_id: nosoykamikaze:)31 }
          - { job_index: 31, job_id: nosoykamikaze:)32 }
          - { job_index: 32, job_id: nosoykamikaze:)33 }
          - { job_index: 33, job_id: nosoykamikaze:)34 }
          - { job_index: 34, job_id: nosoykamikaze:)35 }
          - { job_index: 35, job_id: nosoykamikaze:)36 }
          - { job_index: 36, job_id: nosoykamikaze:)37 }
          - { job_index: 37, job_id: nosoykamikaze:)38 }
          - { job_index: 38, job_id: nosoykamikaze:)39 }
          - { job_index: 39, job_id: nosoykamikaze:)40 }
          - { job_index: 40, job_id: nosoykamikaze:)41 }
          - { job_index: 41, job_id: nosoykamikaze:)42 }
          - { job_index: 42, job_id: nosoykamikaze:)43 }
          - { job_index: 43, job_id: nosoykamikaze:)44 }
          - { job_index: 44, job_id: nosoykamikaze:)45 }
          - { job_index: 45, job_id: nosoykamikaze:)46 }
          - { job_index: 46, job_id: nosoykamikaze:)47 }
          - { job_index: 47, job_id: nosoykamikaze:)48 }
          - { job_index: 48, job_id: nosoykamikaze:)49 }
          - { job_index: 49, job_id: nosoykamikaze:)50 }
          - { job_index: 50, job_id: nosoykamikaze:)51 }
          - { job_index: 51, job_id: nosoykamikaze:)52 }
          - { job_index: 52, job_id: nosoykamikaze:)53 }
          - { job_index: 53, job_id: nosoykamikaze:)54 }
          - { job_index: 54, job_id: nosoykamikaze:)55 }
          - { job_index: 55, job_id: nosoykamikaze:)56 }
          - { job_index: 56, job_id: nosoykamikaze:)57 }
          - { job_index: 57, job_id: nosoykamikaze:)58 }
          - { job_index: 58, job_id: nosoykamikaze:)59 }
          - { job_index: 59, job_id: nosoykamikaze:)60 }
          - { job_index: 60, job_id: nosoykamikaze:)61 }
          - { job_index: 61, job_id: nosoykamikaze:)62 }
          - { job_index: 62, job_id: nosoykamikaze:)63 }
          - { job_index: 63, job_id: nosoykamikaze:)64 }
          - { job_index: 64, job_id: nosoykamikaze:)65 }
          - { job_index: 65, job_id: nosoykamikaze:)66 }
          - { job_index: 66, job_id: nosoykamikaze:)67 }
          - { job_index: 67, job_id: nosoykamikaze:)68 }
          - { job_index: 68, job_id: nosoykamikaze:)69 }
          - { job_index: 69, job_id: nosoykamikaze:)70 }
          - { job_index: 70, job_id: nosoykamikaze:)71 }
          - { job_index: 71, job_id: nosoykamikaze:)72 }
          - { job_index: 72, job_id: nosoykamikaze:)73 }
          - { job_index: 73, job_id: nosoykamikaze:)74 }
          - { job_index: 74, job_id: nosoykamikaze:)75 }
          - { job_index: 75, job_id: nosoykamikaze:)76 }
          - { job_index: 76, job_id: nosoykamikaze:)77 }
          - { job_index: 77, job_id: nosoykamikaze:)78 }
          - { job_index: 78, job_id: nosoykamikaze:)79 }
          - { job_index: 79, job_id: nosoykamikaze:)80 }
          - { job_index: 80, job_id: nosoykamikaze:)81 }
          - { job_index: 81, job_id: nosoykamikaze:)82 }
          - { job_index: 82, job_id: nosoykamikaze:)83 }
          - { job_index: 83, job_id: nosoykamikaze:)84 }
          - { job_index: 84, job_id: nosoykamikaze:)85 }
          - { job_index: 85, job_id: nosoykamikaze:)86 }
          - { job_index: 86, job_id: nosoykamikaze:)87 }
          - { job_index: 87, job_id: nosoykamikaze:)88 }
          - { job_index: 88, job_id: nosoykamikaze:)89 }
          - { job_index: 89, job_id: nosoykamikaze:)90 }
          - { job_index: 90, job_id: nosoykamikaze:)91 }
          - { job_index: 91, job_id: nosoykamikaze:)92 }
          - { job_index: 92, job_id: nosoykamikaze:)93 }
          - { job_index: 93, job_id: nosoykamikaze:)94 }
          - { job_index: 94, job_id: nosoykamikaze:)95 }
          - { job_index: 95, job_id: nosoykamikaze:)96 }
          - { job_index: 96, job_id: nosoykamikaze:)97 }
          - { job_index: 97, job_id: nosoykamikaze:)98 }
          - { job_index: 98, job_id: nosoykamikaze:)99 }
          - { job_index: 99, job_id: nosoykamikaze:)100 }
          - { job_index: 100, job_id: nosoykamikaze:)101 }
          - { job_index: 101, job_id: nosoykamikaze:)102 }
          - { job_index: 102, job_id: nosoykamikaze:)103 }
          - { job_index: 103, job_id: nosoykamikaze:)104 }
          - { job_index: 104, job_id: nosoykamikaze:)105 }
          - { job_index: 105, job_id: nosoykamikaze:)106 }
          - { job_index: 106, job_id: nosoykamikaze:)107 }
          - { job_index: 107, job_id: nosoykamikaze:)108 }
          - { job_index: 108, job_id: nosoykamikaze:)109 }
          - { job_index: 109, job_id: nosoykamikaze:)110 }
          - { job_index: 110, job_id: nosoykamikaze:)111 }
          - { job_index: 111, job_id: nosoykamikaze:)112 }
          - { job_index: 112, job_id: nosoykamikaze:)113 }
          - { job_index: 113, job_id: nosoykamikaze:)114 }
          - { job_index: 114, job_id: nosoykamikaze:)115 }
          - { job_index: 115, job_id: nosoykamikaze:)116 }
          - { job_index: 116, job_id: nosoykamikaze:)117 }
          - { job_index: 117, job_id: nosoykamikaze:)118 }
          - { job_index: 118, job_id: nosoykamikaze:)119 }
          - { job_index: 119, job_id: nosoykamikaze:)120 }
          - { job_index: 120, job_id: nosoykamikaze:)121 }
          - { job_index: 121, job_id: nosoykamikaze:)122 }
          - { job_index: 122, job_id: nosoykamikaze:)123 }
          - { job_index: 123, job_id: nosoykamikaze:)124 }
          - { job_index: 124, job_id: nosoykamikaze:)125 }
          - { job_index: 125, job_id: nosoykamikaze:)126 }
          - { job_index: 126, job_id: nosoykamikaze:)127 }
          - { job_index: 127, job_id: nosoykamikaze:)128 }
          - { job_index: 128, job_id: nosoykamikaze:)129 }
          - { job_index: 129, job_id: nosoykamikaze:)130 }
          - { job_index: 130, job_id: nosoykamikaze:)131 }
          - { job_index: 131, job_id: nosoykamikaze:)132 }
          - { job_index: 132, job_id: nosoykamikaze:)133 }
          - { job_index: 133, job_id: nosoykamikaze:)134 }
          - { job_index: 134, job_id: nosoykamikaze:)135 }
          - { job_index: 135, job_id: nosoykamikaze:)136 }
          - { job_index: 136, job_id: nosoykamikaze:)137 }
          - { job_index: 137, job_id: nosoykamikaze:)138 }
          - { job_index: 138, job_id: nosoykamikaze:)139 }
          - { job_index: 139, job_id: nosoykamikaze:)140 }
          - { job_index: 140, job_id: nosoykamikaze:)141 }
          - { job_index: 141, job_id: nosoykamikaze:)142 }
          - { job_index: 142, job_id: nosoykamikaze:)143 }
          - { job_index: 143, job_id: nosoykamikaze:)144 }
          - { job_index: 144, job_id: nosoykamikaze:)145 }
          - { job_index: 145, job_id: nosoykamikaze:)146 }
          - { job_index: 146, job_id: nosoykamikaze:)147 }
          - { job_index: 147, job_id: nosoykamikaze:)148 }
          - { job_index: 148, job_id: nosoykamikaze:)149 }
          - { job_index: 149, job_id: nosoykamikaze:)150 }
          - { job_index: 150, job_id: nosoykamikaze:)151 }
          - { job_index: 151, job_id: nosoykamikaze:)152 }
          - { job_index: 152, job_id: nosoykamikaze:)153 }
          - { job_index: 153, job_id: nosoykamikaze:)154 }
          - { job_index: 154, job_id: nosoykamikaze:)155 }
          - { job_index: 155, job_id: nosoykamikaze:)156 }
          - { job_index: 156, job_id: nosoykamikaze:)157 }
          - { job_index: 157, job_id: nosoykamikaze:)158 }
          - { job_index: 158, job_id: nosoykamikaze:)159 }
          - { job_index: 159, job_id: nosoykamikaze:)160 }
          - { job_index: 160, job_id: nosoykamikaze:)161 }
          - { job_index: 161, job_id: nosoykamikaze:)162 }
          - { job_index: 162, job_id: nosoykamikaze:)163 }
          - { job_index: 163, job_id: nosoykamikaze:)164 }
          - { job_index: 164, job_id: nosoykamikaze:)165 }
          - { job_index: 165, job_id: nosoykamikaze:)166 }
          - { job_index: 166, job_id: nosoykamikaze:)167 }
          - { job_index: 167, job_id: nosoykamikaze:)168 }
          - { job_index: 168, job_id: nosoykamikaze:)169 }
          - { job_index: 169, job_id: nosoykamikaze:)170 }
          - { job_index: 170, job_id: nosoykamikaze:)171 }
          - { job_index: 171, job_id: nosoykamikaze:)172 }
          - { job_index: 172, job_id: nosoykamikaze:)173 }
          - { job_index: 173, job_id: nosoykamikaze:)174 }
          - { job_index: 174, job_id: nosoykamikaze:)175 }
          - { job_index: 175, job_id: nosoykamikaze:)176 }
          - { job_index: 176, job_id: nosoykamikaze:)177 }
          - { job_index: 177, job_id: nosoykamikaze:)178 }
          - { job_index: 178, job_id: nosoykamikaze:)179 }
          - { job_index: 179, job_id: nosoykamikaze:)180 }
          - { job_index: 180, job_id: nosoykamikaze:)181 }
          - { job_index: 181, job_id: nosoykamikaze:)182 }
          - { job_index: 182, job_id: nosoykamikaze:)183 }
          - { job_index: 183, job_id: nosoykamikaze:)184 }
          - { job_index: 184, job_id: nosoykamikaze:)185 }
          - { job_index: 185, job_id: nosoykamikaze:)186 }
          - { job_index: 186, job_id: nosoykamikaze:)187 }
          - { job_index: 187, job_id: nosoykamikaze:)188 }
          - { job_index: 188, job_id: nosoykamikaze:)189 }
          - { job_index: 189, job_id: nosoykamikaze:)190 }
          - { job_index: 190, job_id: nosoykamikaze:)191 }
          - { job_index: 191, job_id: nosoykamikaze:)192 }
          - { job_index: 192, job_id: nosoykamikaze:)193 }
          - { job_index: 193, job_id: nosoykamikaze:)194 }
          - { job_index: 194, job_id: nosoykamikaze:)195 }
          - { job_index: 195, job_id: nosoykamikaze:)196 }
          - { job_index: 196, job_id: nosoykamikaze:)197 }
          - { job_index: 197, job_id: nosoykamikaze:)198 }
          - { job_index: 198, job_id: nosoykamikaze:)199 }
          - { job_index: 199, job_id: nosoykamikaze:)200 }
    env:
      HAXBALL_ROOMS: ${{ github.event.inputs.haxball_rooms }}
      MENSAJE: ${{ github.event.inputs.mensaje }}
      LLAMAR_ADMIN: ${{ github.event.inputs.llamar_admin }}
      HAXBALL_PASSWORD: ${{ github.event.inputs.password }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: |
          npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth
          npm ci

      - name: Ejecutar bot
        run: node botsstefano.js
        env:
          JOB_INDEX: ${{ matrix.job_index }}
          JOB_ID: ${{ matrix.job_id }}
        timeout-minutes: 60
