name: nofake

on:
  workflow_dispatch:
    inputs:
      haxball_rooms:
        description: 'Links de las salas (separados por coma)'
        required: true
        default: 'https://www.haxball.com/play?c=1n05nbF698Q,https://www.haxball.com/play?c=2,https://www.haxball.com/play?c=3'
      mensaje:
        description: 'Mensaje principal de los bots'
        required: true
        default: 'Raid por Stefano365p'
      llamar_admin:
        description: 'Mensaje para llamar al administrador'
        required: true
        default: 'admin'
      password:
        description: 'ContraseÃ±a de la sala (opcional)'
        required: false
        default: ''

jobs:
  run-bots:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 27
      matrix:
        include:
          - { job_index: 0, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·1 }
          - { job_index: 1, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·2 }
          - { job_index: 2, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·3 }
          - { job_index: 3, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·4 }
          - { job_index: 4, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·5 }
          - { job_index: 5, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·6 }
          - { job_index: 6, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·7 }
          - { job_index: 7, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·8 }
          - { job_index: 8, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·9 }
          - { job_index: 9, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·10 }
          - { job_index: 10, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·11 }
          - { job_index: 11, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·12 }
          - { job_index: 12, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·13 }
          - { job_index: 13, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·14 }
          - { job_index: 14, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·15 }
          - { job_index: 15, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·16 }
          - { job_index: 16, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·17 }
          - { job_index: 17, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·18 }
          - { job_index: 18, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·19 }
          - { job_index: 19, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·20 }
          - { job_index: 20, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·21 }
          - { job_index: 21, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·22 }
          - { job_index: 22, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·23 }
          - { job_index: 23, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·24 }
          - { job_index: 24, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·25 }
          - { job_index: 25, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·26 }
          - { job_index: 26, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·27 }
          - { job_index: 27, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·28 }
          - { job_index: 28, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·29 }
          - { job_index: 29, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·30 }
          - { job_index: 30, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·31 }
          - { job_index: 31, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·32 }
          - { job_index: 32, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·33 }
          - { job_index: 33, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·34 }
          - { job_index: 34, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·35 }
          - { job_index: 35, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·36 }
          - { job_index: 36, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·37 }
          - { job_index: 37, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·38 }
          - { job_index: 38, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·39 }
          - { job_index: 39, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·40 }
          - { job_index: 40, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·41 }
          - { job_index: 41, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·42 }
          - { job_index: 42, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·43 }
          - { job_index: 43, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·44 }
          - { job_index: 44, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·45 }
          - { job_index: 45, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·46 }
          - { job_index: 46, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·47 }
          - { job_index: 47, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·48 }
          - { job_index: 48, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·49 }
          - { job_index: 49, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·50 }
          - { job_index: 50, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·51 }
          - { job_index: 51, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·52 }
          - { job_index: 52, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·53 }
          - { job_index: 53, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·54 }
          - { job_index: 54, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·55 }
          - { job_index: 55, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·56 }
          - { job_index: 56, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·57 }
          - { job_index: 57, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·58 }
          - { job_index: 58, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·59 }
          - { job_index: 59, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·60 }
          - { job_index: 60, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·61 }
          - { job_index: 61, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·62 }
          - { job_index: 62, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·63 }
          - { job_index: 63, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·64 }
          - { job_index: 64, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·65 }
          - { job_index: 65, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·66 }
          - { job_index: 66, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·67 }
          - { job_index: 67, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·68 }
          - { job_index: 68, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·69 }
          - { job_index: 69, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·70 }
          - { job_index: 70, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·71 }
          - { job_index: 71, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·72 }
          - { job_index: 72, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·73 }
          - { job_index: 73, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·74 }
          - { job_index: 74, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·75 }
          - { job_index: 75, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·76 }
          - { job_index: 76, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·77 }
          - { job_index: 77, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·78 }
          - { job_index: 78, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·79 }
          - { job_index: 79, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·80 }
          - { job_index: 80, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·81 }
          - { job_index: 81, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·82 }
          - { job_index: 82, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·83 }
          - { job_index: 83, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·84 }
          - { job_index: 84, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·85 }
          - { job_index: 85, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·86 }
          - { job_index: 86, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·87 }
          - { job_index: 87, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·88 }
          - { job_index: 88, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·89 }
          - { job_index: 89, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·90 }
          - { job_index: 90, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·91 }
          - { job_index: 91, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·92 }
          - { job_index: 92, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·93 }
          - { job_index: 93, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·94 }
          - { job_index: 94, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·95 }
          - { job_index: 95, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·96 }
          - { job_index: 96, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·97 }
          - { job_index: 97, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·98 }
          - { job_index: 98, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·99 }
          - { job_index: 99, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·100 }
          - { job_index: 100, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·101 }
          - { job_index: 101, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·102 }
          - { job_index: 102, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·103 }
          - { job_index: 103, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·104 }
          - { job_index: 104, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·105 }
          - { job_index: 105, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·106 }
          - { job_index: 106, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·107 }
          - { job_index: 107, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·108 }
          - { job_index: 108, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·109 }
          - { job_index: 109, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·110 }
          - { job_index: 110, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·111 }
          - { job_index: 111, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·112 }
          - { job_index: 112, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·113 }
          - { job_index: 113, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·114 }
          - { job_index: 114, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·115 }
          - { job_index: 115, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·116 }
          - { job_index: 116, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·117 }
          - { job_index: 117, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·118 }
          - { job_index: 118, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·119 }
          - { job_index: 119, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·120 }
          - { job_index: 120, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·121 }
          - { job_index: 121, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·122 }
          - { job_index: 122, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·123 }
          - { job_index: 123, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·124 }
          - { job_index: 124, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·125 }
          - { job_index: 125, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·126 }
          - { job_index: 126, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·127 }
          - { job_index: 127, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·128 }
          - { job_index: 128, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·129 }
          - { job_index: 129, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·130 }
          - { job_index: 130, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·131 }
          - { job_index: 131, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·132 }
          - { job_index: 132, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·133 }
          - { job_index: 133, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·134 }
          - { job_index: 134, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·135 }
          - { job_index: 135, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·136 }
          - { job_index: 136, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·137 }
          - { job_index: 137, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·138 }
          - { job_index: 138, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·139 }
          - { job_index: 139, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·140 }
          - { job_index: 140, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·141 }
          - { job_index: 141, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·142 }
          - { job_index: 142, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·143 }
          - { job_index: 143, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·144 }
          - { job_index: 144, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·145 }
          - { job_index: 145, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·146 }
          - { job_index: 146, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·147 }
          - { job_index: 147, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·148 }
          - { job_index: 148, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·149 }
          - { job_index: 149, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·150 }
          - { job_index: 150, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·151 }
          - { job_index: 151, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·152 }
          - { job_index: 152, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·153 }
          - { job_index: 153, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·154 }
          - { job_index: 154, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·155 }
          - { job_index: 155, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·156 }
          - { job_index: 156, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·157 }
          - { job_index: 157, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·158 }
          - { job_index: 158, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·159 }
          - { job_index: 159, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·160 }
          - { job_index: 160, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·161 }
          - { job_index: 161, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·162 }
          - { job_index: 162, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·163 }
          - { job_index: 163, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·164 }
          - { job_index: 164, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·165 }
          - { job_index: 165, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·166 }
          - { job_index: 166, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·167 }
          - { job_index: 167, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·168 }
          - { job_index: 168, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·169 }
          - { job_index: 169, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·170 }
          - { job_index: 170, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·171 }
          - { job_index: 171, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·172 }
          - { job_index: 172, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·173 }
          - { job_index: 173, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·174 }
          - { job_index: 174, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·175 }
          - { job_index: 175, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·176 }
          - { job_index: 176, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·177 }
          - { job_index: 177, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·178 }
          - { job_index: 178, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·179 }
          - { job_index: 179, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·180 }
          - { job_index: 180, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·181 }
          - { job_index: 181, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·182 }
          - { job_index: 182, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·183 }
          - { job_index: 183, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·184 }
          - { job_index: 184, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·185 }
          - { job_index: 185, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·186 }
          - { job_index: 186, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·187 }
          - { job_index: 187, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·188 }
          - { job_index: 188, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·189 }
          - { job_index: 189, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·190 }
          - { job_index: 190, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·191 }
          - { job_index: 191, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·192 }
          - { job_index: 192, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·193 }
          - { job_index: 193, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·194 }
          - { job_index: 194, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·195 }
          - { job_index: 195, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·196 }
          - { job_index: 196, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·197 }
          - { job_index: 197, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·198 }
          - { job_index: 198, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·199 }
          - { job_index: 199, job_id: âš”â˜†(ğ°_ğ°)â˜†ğŸ‡¦ğŸ‡·200 }
    env:
      HAXBALL_ROOMS: ${{ github.event.inputs.haxball_rooms }}
      MENSAJE: ${{ github.event.inputs.mensaje }}
      LLAMAR_ADMIN: ${{ github.event.inputs.llamar_admin }}
      HAXBALL_PASSWORD: ${{ github.event.inputs.password }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: |
          npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth
          npm ci

      - name: Ejecutar bot
        run: node botsstefano.js
        env:
          JOB_INDEX: ${{ matrix.job_index }}
          JOB_ID: ${{ matrix.job_id }}
        timeout-minutes: 60
