name: nofake

on:
  workflow_dispatch:
    inputs:
      haxball_rooms:
        description: 'Links de las salas (separados por coma)'
        required: true
        default: 'https://www.haxball.com/play?c=1n05nbF698Q,https://www.haxball.com/play?c=2,https://www.haxball.com/play?c=3'
      mensaje:
        description: 'Mensaje principal de los bots'
        required: true
        default: 'Raid por Stefano365p'
      llamar_admin:
        description: 'Mensaje para llamar al administrador'
        required: true
        default: 'admin'
      password:
        description: 'Contrase√±a de la sala (opcional)'
        required: false
        default: ''

jobs:
  run-bots:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 27
      matrix:
        include:
          - { job_index: 0, job_id: EZDDOSBYThunderLeonShock1 }
          - { job_index: 1, job_id: EZDDOSBYThunderLeonShock2 }
          - { job_index: 2, job_id: EZDDOSBYThunderLeonShock3 }
          - { job_index: 3, job_id: EZDDOSBYThunderLeonShock4 }
          - { job_index: 4, job_id: EZDDOSBYThunderLeonShock5 }
          - { job_index: 5, job_id: EZDDOSBYThunderLeonShock6 }
          - { job_index: 6, job_id: EZDDOSBYThunderLeonShock7 }
          - { job_index: 7, job_id: EZDDOSBYThunderLeonShock8 }
          - { job_index: 8, job_id: EZDDOSBYThunderLeonShock9 }
          - { job_index: 9, job_id: EZDDOSBYThunderLeonShock10 }
          - { job_index: 10, job_id: EZDDOSBYThunderLeonShock11 }
          - { job_index: 11, job_id: EZDDOSBYThunderLeonShock12 }
          - { job_index: 12, job_id: EZDDOSBYThunderLeonShock13 }
          - { job_index: 13, job_id: EZDDOSBYThunderLeonShock14 }
          - { job_index: 14, job_id: EZDDOSBYThunderLeonShock15 }
          - { job_index: 15, job_id: EZDDOSBYThunderLeonShock16 }
          - { job_index: 16, job_id: EZDDOSBYThunderLeonShock17 }
          - { job_index: 17, job_id: EZDDOSBYThunderLeonShock18 }
          - { job_index: 18, job_id: EZDDOSBYThunderLeonShock19 }
          - { job_index: 19, job_id: EZDDOSBYThunderLeonShock20 }
          - { job_index: 20, job_id: EZDDOSBYThunderLeonShock21 }
          - { job_index: 21, job_id: EZDDOSBYThunderLeonShock22 }
          - { job_index: 22, job_id: EZDDOSBYThunderLeonShock23 }
          - { job_index: 23, job_id: EZDDOSBYThunderLeonShock24 }
          - { job_index: 24, job_id: EZDDOSBYThunderLeonShock25 }
          - { job_index: 25, job_id: EZDDOSBYThunderLeonShock26 }
          - { job_index: 26, job_id: EZDDOSBYThunderLeonShock27 }
          - { job_index: 27, job_id: EZDDOSBYThunderLeonShock28 }
          - { job_index: 28, job_id: EZDDOSBYThunderLeonShock29 }
          - { job_index: 29, job_id: EZDDOSBYThunderLeonShock30 }
          - { job_index: 30, job_id: EZDDOSBYThunderLeonShock31 }
          - { job_index: 31, job_id: EZDDOSBYThunderLeonShock32 }
          - { job_index: 32, job_id: EZDDOSBYThunderLeonShock33 }
          - { job_index: 33, job_id: EZDDOSBYThunderLeonShock34 }
          - { job_index: 34, job_id: EZDDOSBYThunderLeonShock35 }
          - { job_index: 35, job_id: EZDDOSBYThunderLeonShock36 }
          - { job_index: 36, job_id: EZDDOSBYThunderLeonShock37 }
          - { job_index: 37, job_id: EZDDOSBYThunderLeonShock38 }
          - { job_index: 38, job_id: EZDDOSBYThunderLeonShock39 }
          - { job_index: 39, job_id: EZDDOSBYThunderLeonShock40 }
          - { job_index: 40, job_id: EZDDOSBYThunderLeonShock41 }
          - { job_index: 41, job_id: EZDDOSBYThunderLeonShock42 }
          - { job_index: 42, job_id: EZDDOSBYThunderLeonShock43 }
          - { job_index: 43, job_id: EZDDOSBYThunderLeonShock44 }
          - { job_index: 44, job_id: EZDDOSBYThunderLeonShock45 }
          - { job_index: 45, job_id: EZDDOSBYThunderLeonShock46 }
          - { job_index: 46, job_id: EZDDOSBYThunderLeonShock47 }
          - { job_index: 47, job_id: EZDDOSBYThunderLeonShock48 }
          - { job_index: 48, job_id: EZDDOSBYThunderLeonShock49 }
          - { job_index: 49, job_id: EZDDOSBYThunderLeonShock50 }
          - { job_index: 50, job_id: EZDDOSBYThunderLeonShock51 }
          - { job_index: 51, job_id: EZDDOSBYThunderLeonShock52 }
          - { job_index: 52, job_id: EZDDOSBYThunderLeonShock53 }
          - { job_index: 53, job_id: EZDDOSBYThunderLeonShock54 }
          - { job_index: 54, job_id: EZDDOSBYThunderLeonShock55 }
          - { job_index: 55, job_id: EZDDOSBYThunderLeonShock56 }
          - { job_index: 56, job_id: EZDDOSBYThunderLeonShock57 }
          - { job_index: 57, job_id: EZDDOSBYThunderLeonShock58 }
          - { job_index: 58, job_id: EZDDOSBYThunderLeonShock59 }
          - { job_index: 59, job_id: EZDDOSBYThunderLeonShock60 }
          - { job_index: 60, job_id: EZDDOSBYThunderLeonShock61 }
          - { job_index: 61, job_id: EZDDOSBYThunderLeonShock62 }
          - { job_index: 62, job_id: EZDDOSBYThunderLeonShock63 }
          - { job_index: 63, job_id: EZDDOSBYThunderLeonShock64 }
          - { job_index: 64, job_id: EZDDOSBYThunderLeonShock65 }
          - { job_index: 65, job_id: EZDDOSBYThunderLeonShock66 }
          - { job_index: 66, job_id: EZDDOSBYThunderLeonShock67 }
          - { job_index: 67, job_id: EZDDOSBYThunderLeonShock68 }
          - { job_index: 68, job_id: EZDDOSBYThunderLeonShock69 }
          - { job_index: 69, job_id: EZDDOSBYThunderLeonShock70 }
          - { job_index: 70, job_id: EZDDOSBYThunderLeonShock71 }
          - { job_index: 71, job_id: EZDDOSBYThunderLeonShock72 }
          - { job_index: 72, job_id: EZDDOSBYThunderLeonShock73 }
          - { job_index: 73, job_id: EZDDOSBYThunderLeonShock74 }
          - { job_index: 74, job_id: EZDDOSBYThunderLeonShock75 }
          - { job_index: 75, job_id: EZDDOSBYThunderLeonShock76 }
          - { job_index: 76, job_id: EZDDOSBYThunderLeonShock77 }
          - { job_index: 77, job_id: EZDDOSBYThunderLeonShock78 }
          - { job_index: 78, job_id: EZDDOSBYThunderLeonShock79 }
          - { job_index: 79, job_id: EZDDOSBYThunderLeonShock80 }
          - { job_index: 80, job_id: EZDDOSBYThunderLeonShock81 }
          - { job_index: 81, job_id: EZDDOSBYThunderLeonShock82 }
          - { job_index: 82, job_id: EZDDOSBYThunderLeonShock83 }
          - { job_index: 83, job_id: EZDDOSBYThunderLeonShock84 }
          - { job_index: 84, job_id: EZDDOSBYThunderLeonShock85 }
          - { job_index: 85, job_id: EZDDOSBYThunderLeonShock86 }
          - { job_index: 86, job_id: EZDDOSBYThunderLeonShock87 }
          - { job_index: 87, job_id: EZDDOSBYThunderLeonShock88 }
          - { job_index: 88, job_id: EZDDOSBYThunderLeonShock89 }
          - { job_index: 89, job_id: EZDDOSBYThunderLeonShock90 }
          - { job_index: 90, job_id: EZDDOSBYThunderLeonShock91 }
          - { job_index: 91, job_id: EZDDOSBYThunderLeonShock92 }
          - { job_index: 92, job_id: EZDDOSBYThunderLeonShock93 }
          - { job_index: 93, job_id: EZDDOSBYThunderLeonShock94 }
          - { job_index: 94, job_id: EZDDOSBYThunderLeonShock95 }
          - { job_index: 95, job_id: EZDDOSBYThunderLeonShock96 }
          - { job_index: 96, job_id: EZDDOSBYThunderLeonShock97 }
          - { job_index: 97, job_id: EZDDOSBYThunderLeonShock98 }
          - { job_index: 98, job_id: EZDDOSBYThunderLeonShock99 }
          - { job_index: 99, job_id: EZDDOSBYThunderLeonShock100 }
          - { job_index: 100, job_id: EZDDOSBYThunderLeonShock101 }
          - { job_index: 101, job_id: EZDDOSBYThunderLeonShock102 }
          - { job_index: 102, job_id: EZDDOSBYThunderLeonShock103 }
          - { job_index: 103, job_id: EZDDOSBYThunderLeonShock104 }
          - { job_index: 104, job_id: EZDDOSBYThunderLeonShock105 }
          - { job_index: 105, job_id: EZDDOSBYThunderLeonShock106 }
          - { job_index: 106, job_id: EZDDOSBYThunderLeonShock107 }
          - { job_index: 107, job_id: EZDDOSBYThunderLeonShock108 }
          - { job_index: 108, job_id: EZDDOSBYThunderLeonShock109 }
          - { job_index: 109, job_id: EZDDOSBYThunderLeonShock110 }
          - { job_index: 110, job_id: EZDDOSBYThunderLeonShock111 }
          - { job_index: 111, job_id: EZDDOSBYThunderLeonShock112 }
          - { job_index: 112, job_id: EZDDOSBYThunderLeonShock113 }
          - { job_index: 113, job_id: EZDDOSBYThunderLeonShock114 }
          - { job_index: 114, job_id: EZDDOSBYThunderLeonShock115 }
          - { job_index: 115, job_id: EZDDOSBYThunderLeonShock116 }
          - { job_index: 116, job_id: EZDDOSBYThunderLeonShock117 }
          - { job_index: 117, job_id: EZDDOSBYThunderLeonShock118 }
          - { job_index: 118, job_id: EZDDOSBYThunderLeonShock119 }
          - { job_index: 119, job_id: EZDDOSBYThunderLeonShock120 }
          - { job_index: 120, job_id: EZDDOSBYThunderLeonShock121 }
          - { job_index: 121, job_id: EZDDOSBYThunderLeonShock122 }
          - { job_index: 122, job_id: EZDDOSBYThunderLeonShock123 }
          - { job_index: 123, job_id: EZDDOSBYThunderLeonShock124 }
          - { job_index: 124, job_id: EZDDOSBYThunderLeonShock125 }
          - { job_index: 125, job_id: EZDDOSBYThunderLeonShock126 }
          - { job_index: 126, job_id: EZDDOSBYThunderLeonShock127 }
          - { job_index: 127, job_id: EZDDOSBYThunderLeonShock128 }
          - { job_index: 128, job_id: EZDDOSBYThunderLeonShock129 }
          - { job_index: 129, job_id: EZDDOSBYThunderLeonShock130 }
          - { job_index: 130, job_id: EZDDOSBYThunderLeonShock131 }
          - { job_index: 131, job_id: EZDDOSBYThunderLeonShock132 }
          - { job_index: 132, job_id: EZDDOSBYThunderLeonShock133 }
          - { job_index: 133, job_id: EZDDOSBYThunderLeonShock134 }
          - { job_index: 134, job_id: EZDDOSBYThunderLeonShock135 }
          - { job_index: 135, job_id: EZDDOSBYThunderLeonShock136 }
          - { job_index: 136, job_id: EZDDOSBYThunderLeonShock137 }
          - { job_index: 137, job_id: EZDDOSBYThunderLeonShock138 }
          - { job_index: 138, job_id: EZDDOSBYThunderLeonShock139 }
          - { job_index: 139, job_id: EZDDOSBYThunderLeonShock140 }
          - { job_index: 140, job_id: EZDDOSBYThunderLeonShock141 }
          - { job_index: 141, job_id: EZDDOSBYThunderLeonShock142 }
          - { job_index: 142, job_id: EZDDOSBYThunderLeonShock143 }
          - { job_index: 143, job_id: EZDDOSBYThunderLeonShock144 }
          - { job_index: 144, job_id: EZDDOSBYThunderLeonShock145 }
          - { job_index: 145, job_id: EZDDOSBYThunderLeonShock146 }
          - { job_index: 146, job_id: EZDDOSBYThunderLeonShock147 }
          - { job_index: 147, job_id: EZDDOSBYThunderLeonShock148 }
          - { job_index: 148, job_id: EZDDOSBYThunderLeonShock149 }
          - { job_index: 149, job_id: EZDDOSBYThunderLeonShock150 }
          - { job_index: 150, job_id: EZDDOSBYThunderLeonShock151 }
          - { job_index: 151, job_id: EZDDOSBYThunderLeonShock152 }
          - { job_index: 152, job_id: EZDDOSBYThunderLeonShock153 }
          - { job_index: 153, job_id: EZDDOSBYThunderLeonShock154 }
          - { job_index: 154, job_id: EZDDOSBYThunderLeonShock155 }
          - { job_index: 155, job_id: EZDDOSBYThunderLeonShock156 }
          - { job_index: 156, job_id: EZDDOSBYThunderLeonShock157 }
          - { job_index: 157, job_id: EZDDOSBYThunderLeonShock158 }
          - { job_index: 158, job_id: EZDDOSBYThunderLeonShock159 }
          - { job_index: 159, job_id: EZDDOSBYThunderLeonShock160 }
          - { job_index: 160, job_id: EZDDOSBYThunderLeonShock161 }
          - { job_index: 161, job_id: EZDDOSBYThunderLeonShock162 }
          - { job_index: 162, job_id: EZDDOSBYThunderLeonShock163 }
          - { job_index: 163, job_id: EZDDOSBYThunderLeonShock164 }
          - { job_index: 164, job_id: EZDDOSBYThunderLeonShock165 }
          - { job_index: 165, job_id: EZDDOSBYThunderLeonShock166 }
          - { job_index: 166, job_id: EZDDOSBYThunderLeonShock167 }
          - { job_index: 167, job_id: EZDDOSBYThunderLeonShock168 }
          - { job_index: 168, job_id: EZDDOSBYThunderLeonShock169 }
          - { job_index: 169, job_id: EZDDOSBYThunderLeonShock170 }
          - { job_index: 170, job_id: EZDDOSBYThunderLeonShock171 }
          - { job_index: 171, job_id: EZDDOSBYThunderLeonShock172 }
          - { job_index: 172, job_id: EZDDOSBYThunderLeonShock173 }
          - { job_index: 173, job_id: EZDDOSBYThunderLeonShock174 }
          - { job_index: 174, job_id: EZDDOSBYThunderLeonShock175 }
          - { job_index: 175, job_id: EZDDOSBYThunderLeonShock176 }
          - { job_index: 176, job_id: EZDDOSBYThunderLeonShock177 }
          - { job_index: 177, job_id: EZDDOSBYThunderLeonShock178 }
          - { job_index: 178, job_id: EZDDOSBYThunderLeonShock179 }
          - { job_index: 179, job_id: EZDDOSBYThunderLeonShock180 }
          - { job_index: 180, job_id: EZDDOSBYThunderLeonShock181 }
          - { job_index: 181, job_id: EZDDOSBYThunderLeonShock182 }
          - { job_index: 182, job_id: EZDDOSBYThunderLeonShock183 }
          - { job_index: 183, job_id: EZDDOSBYThunderLeonShock184 }
          - { job_index: 184, job_id: EZDDOSBYThunderLeonShock185 }
          - { job_index: 185, job_id: EZDDOSBYThunderLeonShock186 }
          - { job_index: 186, job_id: EZDDOSBYThunderLeonShock187 }
          - { job_index: 187, job_id: EZDDOSBYThunderLeonShock188 }
          - { job_index: 188, job_id: EZDDOSBYThunderLeonShock189 }
          - { job_index: 189, job_id: EZDDOSBYThunderLeonShock190 }
          - { job_index: 190, job_id: EZDDOSBYThunderLeonShock191 }
          - { job_index: 191, job_id: EZDDOSBYThunderLeonShock192 }
          - { job_index: 192, job_id: EZDDOSBYThunderLeonShock193 }
          - { job_index: 193, job_id: EZDDOSBYThunderLeonShock194 }
          - { job_index: 194, job_id: EZDDOSBYThunderLeonShock195 }
          - { job_index: 195, job_id: EZDDOSBYThunderLeonShock196 }
          - { job_index: 196, job_id: EZDDOSBYThunderLeonShock197 }
          - { job_index: 197, job_id: EZDDOSBYThunderLeonShock198 }
          - { job_index: 198, job_id: EZDDOSBYThunderLeonShock199 }
          - { job_index: 199, job_id: EZDDOSBYThunderLeonShock200 }
    env:
      HAXBALL_ROOMS: ${{ github.event.inputs.haxball_rooms }}
      MENSAJE: ${{ github.event.inputs.mensaje }}
      LLAMAR_ADMIN: ${{ github.event.inputs.llamar_admin }}
      HAXBALL_PASSWORD: ${{ github.event.inputs.password }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: |
          npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth
          npm ci

      - name: Ejecutar bot
        run: node botsstefano.js
        env:
          JOB_INDEX: ${{ matrix.job_index }}
          JOB_ID: ${{ matrix.job_id }}
        timeout-minutes: 60
