name: nofake

on:
  workflow_dispatch:
    inputs:
      haxball_rooms:
        description: 'Links de las salas (separados por coma)'
        required: true
        default: 'https://www.haxball.com/play?c=1n05nbF698Q,https://www.haxball.com/play?c=2,https://www.haxball.com/play?c=3'
      mensaje:
        description: 'Mensaje principal de los bots'
        required: true
        default: 'Raid por Stefano365p'
      llamar_admin:
        description: 'Mensaje para llamar al administrador'
        required: true
        default: 'admin'
      password:
        description: 'Contrase√±a de la sala (opcional)'
        required: false
        default: ''

jobs:
  run-bots:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 27
      matrix:
        include:
          - { job_index: 0, job_id: Bora joga1 }
          - { job_index: 1, job_id: Bora joga2 }
          - { job_index: 2, job_id: Bora joga3 }
          - { job_index: 3, job_id: Bora joga4 }
          - { job_index: 4, job_id: Bora joga5 }
          - { job_index: 5, job_id: Bora joga6 }
          - { job_index: 6, job_id: Bora joga7 }
          - { job_index: 7, job_id: Bora joga8 }
          - { job_index: 8, job_id: Bora joga9 }
          - { job_index: 9, job_id: Bora joga10 }
          - { job_index: 10, job_id: Bora joga11 }
          - { job_index: 11, job_id: Bora joga12 }
          - { job_index: 12, job_id: Bora joga13 }
          - { job_index: 13, job_id: Bora joga14 }
          - { job_index: 14, job_id: Bora joga15 }
          - { job_index: 15, job_id: Bora joga16 }
          - { job_index: 16, job_id: Bora joga17 }
          - { job_index: 17, job_id: Bora joga18 }
          - { job_index: 18, job_id: Bora joga19 }
          - { job_index: 19, job_id: Bora joga20 }
          - { job_index: 20, job_id: Bora joga21 }
          - { job_index: 21, job_id: Bora joga22 }
          - { job_index: 22, job_id: Bora joga23 }
          - { job_index: 23, job_id: Bora joga24 }
          - { job_index: 24, job_id: Bora joga25 }
          - { job_index: 25, job_id: Bora joga26 }
          - { job_index: 26, job_id: Bora joga27 }
          - { job_index: 27, job_id: Bora joga28 }
          - { job_index: 28, job_id: Bora joga29 }
          - { job_index: 29, job_id: Bora joga30 }
          - { job_index: 30, job_id: Bora joga31 }
          - { job_index: 31, job_id: Bora joga32 }
          - { job_index: 32, job_id: Bora joga33 }
          - { job_index: 33, job_id: Bora joga34 }
          - { job_index: 34, job_id: Bora joga35 }
          - { job_index: 35, job_id: Bora joga36 }
          - { job_index: 36, job_id: Bora joga37 }
          - { job_index: 37, job_id: Bora joga38 }
          - { job_index: 38, job_id: Bora joga39 }
          - { job_index: 39, job_id: Bora joga40 }
          - { job_index: 40, job_id: Bora joga41 }
          - { job_index: 41, job_id: Bora joga42 }
          - { job_index: 42, job_id: Bora joga43 }
          - { job_index: 43, job_id: Bora joga44 }
          - { job_index: 44, job_id: Bora joga45 }
          - { job_index: 45, job_id: Bora joga46 }
          - { job_index: 46, job_id: Bora joga47 }
          - { job_index: 47, job_id: Bora joga48 }
          - { job_index: 48, job_id: Bora joga49 }
          - { job_index: 49, job_id: Bora joga50 }
          - { job_index: 50, job_id: Bora joga51 }
          - { job_index: 51, job_id: Bora joga52 }
          - { job_index: 52, job_id: Bora joga53 }
          - { job_index: 53, job_id: Bora joga54 }
          - { job_index: 54, job_id: Bora joga55 }
          - { job_index: 55, job_id: Bora joga56 }
          - { job_index: 56, job_id: Bora joga57 }
          - { job_index: 57, job_id: Bora joga58 }
          - { job_index: 58, job_id: Bora joga59 }
          - { job_index: 59, job_id: Bora joga60 }
          - { job_index: 60, job_id: Bora joga61 }
          - { job_index: 61, job_id: Bora joga62 }
          - { job_index: 62, job_id: Bora joga63 }
          - { job_index: 63, job_id: Bora joga64 }
          - { job_index: 64, job_id: Bora joga65 }
          - { job_index: 65, job_id: Bora joga66 }
          - { job_index: 66, job_id: Bora joga67 }
          - { job_index: 67, job_id: Bora joga68 }
          - { job_index: 68, job_id: Bora joga69 }
          - { job_index: 69, job_id: Bora joga70 }
          - { job_index: 70, job_id: Bora joga71 }
          - { job_index: 71, job_id: Bora joga72 }
          - { job_index: 72, job_id: Bora joga73 }
          - { job_index: 73, job_id: Bora joga74 }
          - { job_index: 74, job_id: Bora joga75 }
          - { job_index: 75, job_id: Bora joga76 }
          - { job_index: 76, job_id: Bora joga77 }
          - { job_index: 77, job_id: Bora joga78 }
          - { job_index: 78, job_id: Bora joga79 }
          - { job_index: 79, job_id: Bora joga80 }
          - { job_index: 80, job_id: Bora joga81 }
          - { job_index: 81, job_id: Bora joga82 }
          - { job_index: 82, job_id: Bora joga83 }
          - { job_index: 83, job_id: Bora joga84 }
          - { job_index: 84, job_id: Bora joga85 }
          - { job_index: 85, job_id: Bora joga86 }
          - { job_index: 86, job_id: Bora joga87 }
          - { job_index: 87, job_id: Bora joga88 }
          - { job_index: 88, job_id: Bora joga89 }
          - { job_index: 89, job_id: Bora joga90 }
          - { job_index: 90, job_id: Bora joga91 }
          - { job_index: 91, job_id: Bora joga92 }
          - { job_index: 92, job_id: Bora joga93 }
          - { job_index: 93, job_id: Bora joga94 }
          - { job_index: 94, job_id: Bora joga95 }
          - { job_index: 95, job_id: Bora joga96 }
          - { job_index: 96, job_id: Bora joga97 }
          - { job_index: 97, job_id: Bora joga98 }
          - { job_index: 98, job_id: Bora joga99 }
          - { job_index: 99, job_id: Bora joga100 }
          - { job_index: 100, job_id: Bora joga101 }
          - { job_index: 101, job_id: Bora joga102 }
          - { job_index: 102, job_id: Bora joga103 }
          - { job_index: 103, job_id: Bora joga104 }
          - { job_index: 104, job_id: Bora joga105 }
          - { job_index: 105, job_id: Bora joga106 }
          - { job_index: 106, job_id: Bora joga107 }
          - { job_index: 107, job_id: Bora joga108 }
          - { job_index: 108, job_id: Bora joga109 }
          - { job_index: 109, job_id: Bora joga110 }
          - { job_index: 110, job_id: Bora joga111 }
          - { job_index: 111, job_id: Bora joga112 }
          - { job_index: 112, job_id: Bora joga113 }
          - { job_index: 113, job_id: Bora joga114 }
          - { job_index: 114, job_id: Bora joga115 }
          - { job_index: 115, job_id: Bora joga116 }
          - { job_index: 116, job_id: Bora joga117 }
          - { job_index: 117, job_id: Bora joga118 }
          - { job_index: 118, job_id: Bora joga119 }
          - { job_index: 119, job_id: Bora joga120 }
          - { job_index: 120, job_id: Bora joga121 }
          - { job_index: 121, job_id: Bora joga122 }
          - { job_index: 122, job_id: Bora joga123 }
          - { job_index: 123, job_id: Bora joga124 }
          - { job_index: 124, job_id: Bora joga125 }
          - { job_index: 125, job_id: Bora joga126 }
          - { job_index: 126, job_id: Bora joga127 }
          - { job_index: 127, job_id: Bora joga128 }
          - { job_index: 128, job_id: Bora joga129 }
          - { job_index: 129, job_id: Bora joga130 }
          - { job_index: 130, job_id: Bora joga131 }
          - { job_index: 131, job_id: Bora joga132 }
          - { job_index: 132, job_id: Bora joga133 }
          - { job_index: 133, job_id: Bora joga134 }
          - { job_index: 134, job_id: Bora joga135 }
          - { job_index: 135, job_id: Bora joga136 }
          - { job_index: 136, job_id: Bora joga137 }
          - { job_index: 137, job_id: Bora joga138 }
          - { job_index: 138, job_id: Bora joga139 }
          - { job_index: 139, job_id: Bora joga140 }
          - { job_index: 140, job_id: Bora joga141 }
          - { job_index: 141, job_id: Bora joga142 }
          - { job_index: 142, job_id: Bora joga143 }
          - { job_index: 143, job_id: Bora joga144 }
          - { job_index: 144, job_id: Bora joga145 }
          - { job_index: 145, job_id: Bora joga146 }
          - { job_index: 146, job_id: Bora joga147 }
          - { job_index: 147, job_id: Bora joga148 }
          - { job_index: 148, job_id: Bora joga149 }
          - { job_index: 149, job_id: Bora joga150 }
          - { job_index: 150, job_id: Bora joga151 }
          - { job_index: 151, job_id: Bora joga152 }
          - { job_index: 152, job_id: Bora joga153 }
          - { job_index: 153, job_id: Bora joga154 }
          - { job_index: 154, job_id: Bora joga155 }
          - { job_index: 155, job_id: Bora joga156 }
          - { job_index: 156, job_id: Bora joga157 }
          - { job_index: 157, job_id: Bora joga158 }
          - { job_index: 158, job_id: Bora joga159 }
          - { job_index: 159, job_id: Bora joga160 }
          - { job_index: 160, job_id: Bora joga161 }
          - { job_index: 161, job_id: Bora joga162 }
          - { job_index: 162, job_id: Bora joga163 }
          - { job_index: 163, job_id: Bora joga164 }
          - { job_index: 164, job_id: Bora joga165 }
          - { job_index: 165, job_id: Bora joga166 }
          - { job_index: 166, job_id: Bora joga167 }
          - { job_index: 167, job_id: Bora joga168 }
          - { job_index: 168, job_id: Bora joga169 }
          - { job_index: 169, job_id: Bora joga170 }
          - { job_index: 170, job_id: Bora joga171 }
          - { job_index: 171, job_id: Bora joga172 }
          - { job_index: 172, job_id: Bora joga173 }
          - { job_index: 173, job_id: Bora joga174 }
          - { job_index: 174, job_id: Bora joga175 }
          - { job_index: 175, job_id: Bora joga176 }
          - { job_index: 176, job_id: Bora joga177 }
          - { job_index: 177, job_id: Bora joga178 }
          - { job_index: 178, job_id: Bora joga179 }
          - { job_index: 179, job_id: Bora joga180 }
          - { job_index: 180, job_id: Bora joga181 }
          - { job_index: 181, job_id: Bora joga182 }
          - { job_index: 182, job_id: Bora joga183 }
          - { job_index: 183, job_id: Bora joga184 }
          - { job_index: 184, job_id: Bora joga185 }
          - { job_index: 185, job_id: Bora joga186 }
          - { job_index: 186, job_id: Bora joga187 }
          - { job_index: 187, job_id: Bora joga188 }
          - { job_index: 188, job_id: Bora joga189 }
          - { job_index: 189, job_id: Bora joga190 }
          - { job_index: 190, job_id: Bora joga191 }
          - { job_index: 191, job_id: Bora joga192 }
          - { job_index: 192, job_id: Bora joga193 }
          - { job_index: 193, job_id: Bora joga194 }
          - { job_index: 194, job_id: Bora joga195 }
          - { job_index: 195, job_id: Bora joga196 }
          - { job_index: 196, job_id: Bora joga197 }
          - { job_index: 197, job_id: Bora joga198 }
          - { job_index: 198, job_id: Bora joga199 }
          - { job_index: 199, job_id: Bora joga200 }
    env:
      HAXBALL_ROOMS: ${{ github.event.inputs.haxball_rooms }}
      MENSAJE: ${{ github.event.inputs.mensaje }}
      LLAMAR_ADMIN: ${{ github.event.inputs.llamar_admin }}
      HAXBALL_PASSWORD: ${{ github.event.inputs.password }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: |
          npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth
          npm ci

      - name: Ejecutar bot
        run: node botsstefano.js
        env:
          JOB_INDEX: ${{ matrix.job_index }}
          JOB_ID: ${{ matrix.job_id }}
        timeout-minutes: 60
