name: Kick Viewer Bot

on:
  workflow_dispatch:
    inputs:
      channel:
        description: "Nombre del canal de Kick"
        required: true
        default: "anibalxx-x"
      viewers:
        description: "Cantidad de viewers a enviar"
        required: false
        default: "250"

jobs:
  viewer-bot:
    name: runner-${{ matrix.id }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        id: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]

    env:
      CHANNEL: ${{ github.event.inputs.channel }}
      VIEWERS: ${{ github.event.inputs.viewers }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run viewer bot
        run: |
          echo "Running job ID ${{ matrix.id }} for channel: $CHANNEL"
          python main.py
