name: Kick Multi-Job Bot

on:
  workflow_dispatch:

jobs:
  bot1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run bot 1
        env:
          CLIENT_TOKEN: ${{ secrets.CLIENT_TOKEN }}
          CHANNEL: canal_unico
          VIEWERS: 250
        run: python bot.py

  bot2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run bot 2
        env:
          CLIENT_TOKEN: ${{ secrets.CLIENT_TOKEN }}
          CHANNEL: canal_unico
          VIEWERS: 250
        run: python bot.py

  bot3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run bot 3
        env:
          CLIENT_TOKEN: ${{ secrets.CLIENT_TOKEN }}
          CHANNEL: canal_unico
          VIEWERS: 250
        run: python bot.py

  bot4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run bot 4
        env:
          CLIENT_TOKEN: ${{ secrets.CLIENT_TOKEN }}
          CHANNEL: canal_unico
          VIEWERS: 250
        run: python bot.py

  bot5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run bot 5
        env:
          CLIENT_TOKEN: ${{ secrets.CLIENT_TOKEN }}
          CHANNEL: canal_unico
          VIEWERS: 250
        run: python bot.py

  bot6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run bot 6
        env:
          CLIENT_TOKEN: ${{ secrets.CLIENT_TOKEN }}
          CHANNEL: canal_unico
          VIEWERS: 250
        run: python bot.py

  bot7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run bot 7
        env:
          CLIENT_TOKEN: ${{ secrets.CLIENT_TOKEN }}
          CHANNEL: canal_unico
          VIEWERS: 250
        run: python bot.py

  bot8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run bot 8
        env:
          CLIENT_TOKEN: ${{ secrets.CLIENT_TOKEN }}
          CHANNEL: canal_unico
          VIEWERS: 250
        run: python bot.py

  bot9:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run bot 9
        env:
          CLIENT_TOKEN: ${{ secrets.CLIENT_TOKEN }}
          CHANNEL: canal_unico
          VIEWERS: 250
        run: python bot.py

  bot10:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run bot 10
        env:
          CLIENT_TOKEN: ${{ secrets.CLIENT_TOKEN }}
          CHANNEL: canal_unico
          VIEWERS: 250
        run: python bot.py

  bot11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run bot 11
        env:
          CLIENT_TOKEN: ${{ secrets.CLIENT_TOKEN }}
          CHANNEL: canal_unico
          VIEWERS: 250
        run: python bot.py

  bot12:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run bot 12
        env:
          CLIENT_TOKEN: ${{ secrets.CLIENT_TOKEN }}
          CHANNEL: canal_unico
          VIEWERS: 250
        run: python bot.py

  bot13:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run bot 13
        env:
          CLIENT_TOKEN: ${{ secrets.CLIENT_TOKEN }}
          CHANNEL: canal_unico
          VIEWERS: 250
        run: python bot.py

  bot14:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run bot 14
        env:
          CLIENT_TOKEN: ${{ secrets.CLIENT_TOKEN }}
          CHANNEL: canal_unico
          VIEWERS: 250
        run: python bot.py

  bot15:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run bot 15
        env:
          CLIENT_TOKEN: ${{ secrets.CLIENT_TOKEN }}
          CHANNEL: canal_unico
          VIEWERS: 250
        run: python bot.py

  bot16:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run bot 16
        env:
          CLIENT_TOKEN: ${{ secrets.CLIENT_TOKEN }}
          CHANNEL: canal_unico
          VIEWERS: 250
        run: python bot.py

  bot17:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run bot 17
        env:
          CLIENT_TOKEN: ${{ secrets.CLIENT_TOKEN }}
          CHANNEL: canal_unico
          VIEWERS: 250
        run: python bot.py

  bot18:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run bot 18
        env:
          CLIENT_TOKEN: ${{ secrets.CLIENT_TOKEN }}
          CHANNEL: canal_unico
          VIEWERS: 250
        run: python bot.py

  bot19:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run bot 19
        env:
          CLIENT_TOKEN: ${{ secrets.CLIENT_TOKEN }}
          CHANNEL: canal_unico
          VIEWERS: 250
        run: python bot.py

  bot20:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run bot 20
        env:
          CLIENT_TOKEN: ${{ secrets.CLIENT_TOKEN }}
          CHANNEL: canal_unico
          VIEWERS: 250
        run: python bot.py
